### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kreso22** [jpernst/FixedPointy#1]
Hello,

this is more of a question then an issue.
After I import the library, how do I actually use it (convert to and from FP)?

This is what I do and I am not getting back the result I expect. 

Thanks in advance!

`float someFloat = 9.12345f; //original float`
`int someNum = (int)Math.Round(someFloat * 1000, 3); //convert to int`
`FixedPointy.Fix fp = new FixedPointy.Fix(someNum); //convert to fp`
`FixedPointy.Fix sqrtFp = FixedPointy.FixMath.Sqrt(fp); //perform operation`
`float outNum = (1f * sqrtFp.Raw) / 1000; //convert back to float`

**Comment by jpernst** [comment]
The default constructor takes a raw bit pattern representing a fixed point number, which probably isn't what you want here. Instead, use `Fix.Mix`. In this case you'd do: `Fix.Mix(9, 12345, 100000)`
